### ISSUE TITLE
Won't Install

### ISSUE THREAD

**Issue by jamesmanson34** [Shell-Company/go-scout#3]
`~ cd go-scout`
`~/go-scout go build`

`pkg-config: exec: "pkg-config": executable file not found in $PATH`

**Comment by serosenstein** [comment]
You need to find the package from your distribution that provides pkg-config.  If it's already installed it needs to be in your $PATH like the message mentions, but most distributions would add it automatically or put it in a place that is already in your $PATH.

Arch:
yay -Syu pkgconf

Debian/Ubuntu:
apt-get install pkgconf

Fedora/CentOS/Redhat
dnf install pkgconf

Chances are if you're missing that, you're probably missing other build dependencies and may want to look at installing a 'Development Tools' equivalent group package.
